### ISSUE TITLE
set_squad_assignments Hide doesn't work

### ISSUE THREAD

**Issue by minion6011** [xMistt/rebootpy#11]
<img width="517" alt="image" src="https://github.com/user-attachments/assets/fa62e233-331d-451f-9834-8ce826f573a9">

When I use set_squad_assignments with hide=True on a member the member and the bot will become the leader of the lobby

**Comment by xMistt** [comment]
ill look into it

**Comment by xMistt** [comment]
It seems to work fine for me, I can hide myself while in the bots party, can you share the code you're using to hide yourself?

**Comment by minion6011** [comment]
@discord_bot.command()
async def test(ctx, name, value:str):
	#https://rebootpy.readthedocs.io/en/latest/api.html?highlight=party#rebootpy.ClientParty.set_squad_assignments
	try:
		fn_client = online_fn_client[str(ctx.author.id)]
		user = await fn_client.fetch_user(name)
		party_user = fn_client.party.get_member(user.id)
		assignments_value = {}
		if value == "true":
			assignments_value[party_user] = rebootpy.SquadAssignment(hidden=True)
		elif value == "false":
			assignments_value[party_user] = rebootpy.SquadAssignment(hidden=False)
		await fn_client.party.set_squad_assignments(assignments=assignments_value)
	except Exception as e:
		print(e)

**Comment by xMistt** [comment]
Using that same code seems to work fine for me, are you running 0.9.3 or the latest GitHub version and is the bot party leader?
```python
@bot.command()
async def hide2(ctx, name, value: str) -> None:
    try:
        fn_client = bot
        user = await fn_client.fetch_user(name)
        party_user = fn_client.party.get_member(user.id)
        assignments_value = {}
        if value == "true":
            assignments_value[party_user] = rebootpy.SquadAssignment(
                hidden=True
            )
        elif value == "false":
            assignments_value[party_user] = rebootpy.SquadAssignment(
                hidden=False
            )
        await fn_client.party.set_squad_assignments(
            assignments=assignments_value
        )
    except Exception as e:
        print(e)
```
![image](https://github.com/user-attachments/assets/aba3a04e-6b8f-4d25-a0f2-bb518ce7b0e3)
![image](https://github.com/user-attachments/assets/5afad6f2-ce45-4392-855f-16113f8c473d)

I'm going to add a `.hide()` function to `PartyMember` to make it simpler and please let me know if that fixes the issue for you, I was planning on doing this sometime in the future anyway.

**Comment by minion6011** [comment]
Nope i was running an old version, now i upgraded the version to 0.9.3 the command runs without error but doesn't work it might be a problem if the command is on discord?

**Comment by minion6011** [comment]
the error is because `asyncio.Lock()` / `client_fn.party.edit_lock.locked()` that return false, in the code of the library is used in `party.py` in `refresh_squad_assignments`:

```py
check = not self.edit_lock.locked() if could_be_edit else True
if check:
        #code...
```

**Comment by xMistt** [comment]
Thanks for letting me know, I'll look into it again.

**Comment by xMistt** [comment]
Do you do anything specific before attempting to hide party members? It's never locked for me and I tried multiple times. Also, does hiding always never work?

**Comment by minion6011** [comment]
for me it is locked because the bot is executed inside a function because it is a starbot

**Comment by minion6011** [comment]
any news?

**Comment by xMistt** [comment]
I was very busy recently, it doesn't matter how you start the bot, I'll look into it soon.

**Comment by minion6011** [comment]
I joined the discord server, in which channel should I write?, what is your name on discord?

**Comment by minion6011** [comment]
today i updated the library and the code works, thanks for the help
