### ISSUE TITLE
change back max lengh on help command

### ISSUE THREAD

**Issue by JyhuKo** [xMistt/rebootpy#4]
seems like the max lengh changed again and it is more than 256

**Comment by xMistt** [comment]
do you know the exact value?

**Comment by JyhuKo** [comment]
yeah 2048

**Comment by xMistt** [comment]
thanks for lmk, ill just revert the help changes

**Comment by xMistt** [comment]
reverted in https://github.com/xMistt/rebootpy/commit/715118f499d272c3325235a67edddec19b753388
