### ISSUE TITLE
How to set a cosmetic

### ISSUE THREAD

**Issue by beanpython1** [xMistt/rebootpy#8]
Hello! 

I am wanting to do a 'ghost-equip' kind of thing where I can set my skin to any (even not owned) in my party and other members will see it. However, I cannot find the epic games endpoint for doing so. Could you tell me how? Thanks

**Comment by xMistt** [comment]
you need to patch the meta, you can look at [party_update_member_meta()](https://github.com/xMistt/rebootpy/blob/main/rebootpy/http.py#L1687)
